services:
  web:
    build: .
    # command: >
    #   # sh -c "python manage.py migrate"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - task_manager_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network

networks:
  task_manager_network:

volumes:
  postgres_data: